### ISSUE TITLE
any idea how to fix https://trac.macports.org/ticket/68287

### ISSUE THREAD

**Issue by MStraeten** [wbsoft/python-poppler-qt5#61]
reinstalling on a new mac fails due to a compiler requirement.

**Comment by jeanas** [comment]
I've posted a suggestion on the ticket.

**Comment by chrstphrchvz** [comment]
> I've posted a suggestion on the ticket.

Thanks for the suggestion, I have verified it works (although I have applied it to the end of pyproject.toml so that the patch applies cleanly to both 21.3.0 and current master branch).

**Comment by jeanas** [comment]
Fixed in master.
