### ISSUE TITLE
Document.load fails with any argument

### ISSUE THREAD

**Issue by blindmelon** [wbsoft/python-poppler-qt5#9]
I had some code using this library that previously worked, but now something has changed, not in this library but affecting it. I don't know what.

Now when I use Document.load("path.pdf") I get:

```
TypeError: Document.load(): argument 1 has unexpected type 'str'
```

**Comment by wbsoft** [comment]
Are you using Python 2 or 3 ?

**Comment by blindmelon** [comment]
Python 3

**Comment by wbsoft** [comment]
Maybe you need to specify the filename as a bytes string. Will look into it.

**Comment by mitya57** [comment]
A similar issue was reported against our Debian package today: https://bugs.debian.org/839870.

Passing the bytes string does not work.

**Comment by mitya57** [comment]
@blindmelon Are you using your own build, or the distro package (and if yes, which distro)? I wonder if there is any issue specific to Debian package here. Maybe we need a rebuild against new sip/pyqt5?

**Comment by mitya57** [comment]
As I expected, a simple rebuild fixes the issue. So this is a result of sip ABI instability (hopefully this will be [finally fixed](https://www.riverbankcomputing.com/pipermail/pyqt/2016-September/038136.html) in the next sip version).
